version: "3"

services:
  poker-database:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "poker_easy"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
